name: BabashkaForkPF (Clojure)
description: Run babashka script or babashka shell command(s) on GitHub Actions

author: Tzafrir Ben-Ami

branding:
  color: 'green'
  icon: 'command'

inputs:
  bb_src:
    description: 'path to the babashka script to execute'
    required: false
    default: ''
  bb_url:
    description: 'URL of the babashka script to download and execute'
    required: false
    default: ''
  bb_cmd:
    description: 'shell command(s) piped with babashka command(s) to execute'
    required: false
    default: ''
  bb_args:
    description: 'babashka script arguments (ignored when using with `bb_cmd` command)'
    required: false
    default: ''

outputs:
  bb_out:
    description: 'bb script\command output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--bb_src'
    - ${{ inputs.bb_src }}
    - '--bb_url'
    - ${{ inputs.bb_url }}
    - '--bb_cmd'
    - ${{ inputs.bb_cmd }}
    - '--bb_args'
    - ${{ inputs.bb_args }}

